import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const dataDir = path.join(repoRoot, "data", "valid");
const outputFile = path.join(repoRoot, "supabase", "seed.sql");

// Parent tables must be loaded before tables that reference them.
const tableOrder = [
  "members",
  "membership_plans",
  "staff_accounts",
  "memberships",
  "member_accounts",
  "membership_status_history",
  "membership_pause_requests",
  "class_sessions",
  "reservations",
  "drop_in_payments",
  "notifications",
  "waitlist_promotions",
  "attendance_records",
  "attendance_corrections",
  "risk_assessments",
  "outreach_records",
  "outreach_actions",
  "risk_case_notes",
];

function parseCSV(csv) {
  const rows = [];
  let row = [];
  let value = "";
  let quoted = false;

  for (let index = 0; index < csv.length; index += 1) {
    const character = csv[index];
    if (quoted) {
      if (character === '"' && csv[index + 1] === '"') {
        value += '"';
        index += 1;
      } else if (character === '"') {
        quoted = false;
      } else {
        value += character;
      }
    } else if (character === '"') {
      quoted = true;
    } else if (character === ",") {
      row.push(value);
      value = "";
    } else if (character === "\n") {
      row.push(value.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      value = "";
    } else {
      value += character;
    }
  }

  if (quoted) throw new Error("CSV ends inside a quoted value");
  if (value || row.length) {
    row.push(value.replace(/\r$/, ""));
    rows.push(row);
  }
  return rows;
}

function sqlValue(value) {
  if (value === "") return "null";
  return `'${value.replaceAll("'", "''")}'`;
}

const blocks = [
  "-- Generated from data/valid by generator/build_supabase_seed.mjs.",
  "-- Do not edit this file manually; regenerate it after dataset changes.",
  "begin;",
  "set local statement_timeout = 0;",
  "set local lock_timeout = 0;",
  "set local client_min_messages = warning;",
  "do $$ begin",
  "  if exists (select 1 from public.members limit 1) then",
  "    raise exception 'Pulse Studio seed aborted: database already contains member data';",
  "  end if;",
  "end $$;",
  "",
];

for (const table of tableOrder) {
  const filename = path.join(dataDir, `${table}.csv`);
  if (!fs.existsSync(filename)) throw new Error(`Missing ${filename}`);

  const csv = fs.readFileSync(filename, "utf8");
  const [columns, ...rows] = parseCSV(csv);
  if (!columns || rows.length === 0) throw new Error(`${table}.csv has no data rows`);
  if (rows.some((row) => row.length !== columns.length)) {
    throw new Error(`${table}.csv contains a row with the wrong column count`);
  }

  for (let start = 0; start < rows.length; start += 500) {
    const values = rows
      .slice(start, start + 500)
      .map((row) => `(${row.map(sqlValue).join(", ")})`)
      .join(",\n");
    blocks.push(
      `insert into public.${table} (${columns.join(", ")}) values`,
      `${values};`,
      "",
    );
  }
}

blocks.push("commit;", "");
fs.writeFileSync(outputFile, blocks.join("\n"), "utf8");
console.log(`Created ${path.relative(repoRoot, outputFile)} for ${tableOrder.length} tables.`);
